export interface Participant {
    participantId: number
    teamId: number
    championId: number
    spell1Id: number
    spell2Id: number
    stats: {
        participantId: number
        win: boolean
        item0: number
        item1: number
        item2: number
        item3: number
        item4: number
        item5: number
        item6: number
        kills: number
        deaths: number
        assists: number
        largestKillingSpree: number
        largestMultiKill: number
        killingSprees: number
        longestTimeSpentLiving: number
        doubleKills: number
        tripleKills: number
        quadraKills: number
        pentaKills: number
        unrealKills: number
        totalDamageDealt: number
        magicDamageDealt: number
        physicalDamageDealt: number
        booleanDamageDealt: number
        largestCriticalStrike: number
        totalDamageDealtToChampions: number
        magicDamageDealtToChampions: number
        physicalDamageDealtToChampions: number
        booleanDamageDealtToChampions: number
        totalHeal: number
        totalUnitsHealed: number
        damageSelfMitigated: number
        damageDealtToObjectives: number
        damageDealtToTurrets: number
        visionScore: number
        timeCCingOthers: number
        totalDamageTaken: number
        magicalDamageTaken: number
        physicalDamageTaken: number
        booleanDamageTaken: number
        goldEarned: number
        goldSpent: number
        turretKills: number
        inhibitorKills: number
        totalMinionsKilled: number
        neutralMinionsKilled: number
        neutralMinionsKilledTeamJungle: number
        neutralMinionsKilledEnemyJungle: number
        totalTimeCrowdControlDealt: number
        champLevel: number
        visionWardsBoughtInGame: number
        sightWardsBoughtInGame: number
        wardsPlaced: number
        wardsKilled: number
        firstBloodKill: boolean
        firstBloodAssist: boolean
        firstTowerKill: boolean
        firstTowerAssist: boolean
        combatPlayerScore: number
        objectivePlayerScore: number
        totalPlayerScore: number
        totalScoreRank: number
        statPerknumber: number
    }
}